pipeline:
  test:
    image: node:12-alpine
    secrets: [account_key]
    commands:
      - export CI=true
      - node --version
      - npm --version
      - npm ci
      - npm test
  publish:
    image: plugins/docker
    registry: registry:5000
    insecure: true
    repo: registry:5000/bustimings-2
    tags:
      - latest
    when:
      branch: master
