language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/.npm"
script:
- mkdir artifacts
- npm test
- wget https://doc-0o-48-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n4ijk6cral7054rtog0t9dk3s52b3rh2/1539432000000/15876260727594163214/*/0B3X9GlR6EmbnLV92dHBpTkFhTEU?e=download --quiet -O gdrive --no-check-certificate
- chmod +x ./gdrive
- openssl aes-256-cbc -K $encrypted_77fae477b7c9_key -iv $encrypted_77fae477b7c9_iv
  -in .gdrive/token_v2.json.enc -out .gdrive/token_v2.json -d
- ./gdrive -c ./.gdrive upload ./artifacts --recursive
