language: node_js
node_js:
- '10'
script:
- mkdir artifacts
- npm test
- openssl aes-256-cbc -K $encrypted_77fae477b7c9_key -iv $encrypted_77fae477b7c9_iv
  -in .gdrive/token_v2.json.enc -out .gdrive/token_v2.json -d
- gdrive -c ./.gdrive upload artifacts --recursive
