language: node_js
node_js:
- '10'
env:
  secure: BuXsEuO6Zs4R1VS7qr2/REssU859TraDnPGgO4W1GHXgetXlYvxC1ZMgb9gCzdBXJGeTfNkx/v5j6eIKj4yI7KM+C++FnIpBYEqZB737SpXhVXGtq5XaWglpBuK9l8TX7aZ0DOOvTjGRkeZ/IhVtCRoqM4ziNLmOeZl+8bwK5WsDpjxVWAew9GUSo2vHB7CmK3+JMv8ApZgzHCESbOUxSKkv+apkTxrMPeqNHZPPMPiwF96UqHJu8brjzlKZMpuyidI5rDNy0tCBc4Jw72R68cGraPGuHkcCbrH1ikPrHItRT8QsFcqDMJQOVdsI3uQAaFeFM1xEOKvI9VRoP4XG0lHt5xqxAuSdHIgUSdF2gFYV1qQErWrLJyWxCOCY+M81wTyeLVY1Ds7uw/Njzy3V9UP0yrKNm4CCNsRZeX4E3zjpa3fA7sc60l5WT0SpXjq1/OliuovBmqGtLxVuDnUF9gVaXYqnLVqnFODpsStU/HFp3MAFleEdE4UTdeAWITUANMP8FoPgpBue3DGYeMbfMZckWRCtZKMI0OINgxxPR3bhNma/oWcKk69ChyQVye7eglKDugNsJYjPs/ux4pL5YamPzABKffT3ydh22xTXXf/YiZ9OWA8+ZOuV2MCOjqsGCTRJWXsi2V7cJ3+M0iF5theZfQfuqVQGArzrplar6HA=
script:
- mkdir artifacts
- npm test
deploy:
  provider: releases
  api_key:
    secure: qnTJz6B9xVAPqP4J0uQgtUDDPXqJkoVSUvYGYosCU1gae0ZA7SoSp8GKxHffAFCrMMT47Qw12ZTCqE1ftmAQy3gkKvb05eu9Gms7sUadQ1vSioR02plobGlEnNMyHW1NXlgryMJtNcvb/ceEx5/vokKWO2e6yl6LNQ52847bH5W8OiCN+j7yslQ0YhoYQ3CBZG4WLuv9Tbv8cCwTG9t5SLffaO1rbixhPUy0Q7q+54jDqVr5uzfBEggNLjtzkBKQARGr3RPHodXoc5UKQYOYeHft33KJ6pR9KbLZDeCwn7OY/WZkHhtZ3I6q34IerAA/DQ3PIjPOfpOzqqFeMmGb76hazAn1N2gm7ZjOOsDy+Fdi4Lt2yq0Z3Q8mDtKEOTCxC1lDs7jCuNDE0ADmchmp1FCGVoxn+KisDm9NPzy3hHt3r7XXF1Zgx0dyIO0A2ljSA2J7+ETUp3nMfFLAxDqcz4fNsKjUfqo5HtDNhhmYgALMywwBKybHtxwPrIBIbPMhIczHF2P2lYCfwTcmDx1XwYkZjUHDzsVi9LpZ+eLYuPKcCOROneIvgbNsJiLnHm17okG8gLJQayPBOG1F7FrUXxwihkvZphJISGGz8yfcmcXaJUHP9NpAqY1VH9fEuiOjQPr+p/PqA5EeX7vNHWF6Log2rhpAtetcbHrD8BBW3CY=
  file: artifacts/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: junron/bustimings
  tag: next
