language: node_js
node_js:
- '10'
env:
  secure: BuXsEuO6Zs4R1VS7qr2/REssU859TraDnPGgO4W1GHXgetXlYvxC1ZMgb9gCzdBXJGeTfNkx/v5j6eIKj4yI7KM+C++FnIpBYEqZB737SpXhVXGtq5XaWglpBuK9l8TX7aZ0DOOvTjGRkeZ/IhVtCRoqM4ziNLmOeZl+8bwK5WsDpjxVWAew9GUSo2vHB7CmK3+JMv8ApZgzHCESbOUxSKkv+apkTxrMPeqNHZPPMPiwF96UqHJu8brjzlKZMpuyidI5rDNy0tCBc4Jw72R68cGraPGuHkcCbrH1ikPrHItRT8QsFcqDMJQOVdsI3uQAaFeFM1xEOKvI9VRoP4XG0lHt5xqxAuSdHIgUSdF2gFYV1qQErWrLJyWxCOCY+M81wTyeLVY1Ds7uw/Njzy3V9UP0yrKNm4CCNsRZeX4E3zjpa3fA7sc60l5WT0SpXjq1/OliuovBmqGtLxVuDnUF9gVaXYqnLVqnFODpsStU/HFp3MAFleEdE4UTdeAWITUANMP8FoPgpBue3DGYeMbfMZckWRCtZKMI0OINgxxPR3bhNma/oWcKk69ChyQVye7eglKDugNsJYjPs/ux4pL5YamPzABKffT3ydh22xTXXf/YiZ9OWA8+ZOuV2MCOjqsGCTRJWXsi2V7cJ3+M0iF5theZfQfuqVQGArzrplar6HA=
script:
- mkdir artifacts
- npm test
deploy:
  provider: releases
  api_key:
    secure: FQcyp1KCSdF6jwO5meVkIJOD/cOrMIm3dimvMlCDvcGKnUmK+HfIpGjLQCs2adSB38Pyfc0RhZz5erUb8P4W7zq3d51jHFRNJCH5GKKHTl8U26f/fg5v+av4YyqI8PxylltMDD9eDXMmYD0sGo6A5py0Aw6n1PTrbddn3oOcGHWflPUxumE4HeSaKT+LRetGb62JQEcQXcQQI6P4o+M54vQrVKRBPfdjJgH/v5J4sUHfCbHgG7ZxIcKk3H4pOoLeatLeTQdUkfCct0SA4hdDAL44VCD1KG6LNnC7HZ28PRPqqIk/nDXKtjvWvg1Te4ercUChrsbXET/TIvzRCSm2cCWJkuPnu2HJ6q03YCNFPwKdoWO8EccCmrCs8oiYwrxzl8T0Lt1rk9bAOje+vzioVcY1BtKQMSGxKwcxD6abPqasjaZpeubG9+wrudIJGKYgwFw9EMz1zrBHpe+5creWOeyyFR2t9HVevjLemkTxQQLJ0GAhtEl2TFc5wd8i4roSI3UThrcePSgIxzuK6WPBW0wFR51/su/8aYfDrMpF7axyDvHPVB70oOiSiSf2dM4LsqjlOc0C/PHvnuhNbLdkqHeWORix7QIJKBpPEzQL3457m1C07h4ikEhTqsf93AVzng+lvsYVc7D4Q54D7iVJbd5Xn6vvygxx2u15h16K4qs=
  file: artifacts/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: junron/bustimings
  tag: next
